### ISSUE TITLE
Как установить на Joomla?

### ISSUE THREAD

**Issue by korenevskiy** [tarchevsky/ui-pack#1]
Пишу сайт на Joomla. Вбил в яндексе, CSS UI библиотеки , 4ая, выпала эта ссылка.
Почему нет описания как установить в HTML сайт?
Или у этой библиотеки порог входа значительно выше чем у Bootstrap?
У Bootstrap есть описание как он устанавливается в HTML для тех кто GULP в глаза не видел.
Режим GiHub-Pages могли бы испльзовать для показа DEMO, без скачивания.

**Comment by tarchevsky** [comment]
Библиотека предназначена для работы с HTML и не предназначена для работы с CMS. Если хотите сделать тему для joomla или для какого-либо другого движка, руководствуйтесь документацией движка. Это сборка для комфортной компиляции файлов с готовыми блоками. После запуска команды yarn run build, вы получаете скомпилированные файлы html, css, js. У этой библиотеки порог входа значительно ниже, так как вам не надо привыкать к большому количеству классов, а сам проект значительно меньше и выполняется силами одного разработчика. Если Вас пугает Gulp, Pug, SCSS - осваивайте технологии.

**Comment by tarchevsky** [comment]
Demo-сайт ещё в разработке, как и сайт с документацией.

**Comment by korenevskiy** [comment]
> Demo-сайт ещё в разработке, как и сайт с документацией.

Причём тут CMS, Вам следовало бы указать в описании репозитория что то вроде такого
```HTML
<link rel="stylesheet" href="/css/tezis.min.css" type="text/css" media="all" />
<script src="/js/tezis.min.js"  ></script>
```
Я ДЕМО искал чтобы в нём найти эти строки.
